BAM_DIR: "/scratch/remills_root/remills/arthurz/Nanopore.data.sharing.box/single_cell.nanopore.seq.06.08.22"
OUT_DIR: "/scratch/remills_root/remills99/bbessell/mei_metrics/output"
SAMPLE_INFO_FILEPATH: "/scratch/remills_root/remills99/bbessell/mei_metrics/samp_info.tsv"
PALMER_LOC: "/home/bbessell/software/PALMER/PALMER"
REF_GEN: "/scratch/remills_root/remills/arthurz/Nanopore.data.sharing.box/ref/hg38.no_alt.fa"
REF_VER: "GRCh38"
CHROMOSOMES: "chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY"
MEI: "LINE, ALU, SVA, HERVK"
MODE: "raw"