RAW_DIR: "raw_reads"
PHASED_DIR: "phased_reads"
OUT_DIR: "scratch_ln/output"
SAMPLE_INFO_FILEPATH: "scratch_ln/samp_info.tsv"
PALMER_LOC: "/home/bbessell/software/PALMER/PALMER"
BEDOPS_BIN: "/home/bbessell/software/bedops/bin"
REF_GEN: "/scratch/remills_root/remills/shared_data/Reference/hg38.no_alt.fa"
REF_TAB: "GRCh38.genome"
REF_VER: "GRCh38"
CHROMOSOMES: "chr1, chr2, chr3, chr4, chr5, chr6, chr7, chr9, chr10, chr11, chr12, chr13, chr14, chr15, chr17, chr18, chr19, chr20, chr21, chr22, chrX, chrY"
MEI: "LINE, ALU, SVA, HERVK"
#CHROMOSOMES: "chr21"
#MEI: "SVA"
MODE: "raw"
FILTERS: "hp1, hp2, raw"
POLYMORPHS: "HGSVC.MEI.Master.Set.Tier3.20220909.vcf" # do not include gz extention
P_FILT: 1
